apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-main
  namespace: identity
data:
  keycloak.conf: |
    db = postgres
    db-host = postgres
    db-port = 5432
    db-name = keycloak_db
    db-url = jdbc:postgresql://postgres:5432/keycloak_db?currentSchema=public
    db-url-host = database
    health-enabled = true
    metrics-enabled = true
    #hostname=myhostname
    http-enabled = true
    http-relative-path = /
    http-port = 8080
    https-port = 8443
    hostname-strict = false
    cache = ispn
    log-level = info
    log-console-output = default
    proxy-headers = xforwarded
