apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: identity
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2
          args:
            - start
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PG_ADMIN_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PG_ADMIN_PASSWORD
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: BOOTSTRAP_ADMIN_USERNAME
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: BOOTSTRAP_ADMIN_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
          volumeMounts:
            - mountPath: /opt/keycloak/conf/keycloak.conf
              name: keycloak-main
              subPath: keycloak.conf
      volumes:
        - name: keycloak-main
          configMap:
            name: keycloak-main
