apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: PG_ADMIN_USER
      remoteRef:
        key: app-keycloak-secrets
        property: pg_admin_user
    - secretKey: PG_ADMIN_PASSWORD
      remoteRef:
        key: app-keycloak-secrets
        property: pg_admin_password