apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: transmission-torrent
  namespace: media
spec:
  entryPoints:
    - torrent-udp
  routes:
    - services:
        - name: transmission-torrent
          namespace: media
          port: 51413
          nativeLB: true
