- name: Gathering facts
  ansible.builtin.setup:

- name: Check whether keyrings has already been imported
  ansible.builtin.stat:
    path: /usr/share/keyrings/openmediavault-archive-keyring.gpg
  register: openmediavault_keyring

- name: Identify motherboard
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        package:
          - lshw
          - jq
    - name: Get motherboard name
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          lshw -json -class system | jq '.[0].product'
        executable: /bin/bash
      register: openmediavault_motherboard

- name: Check if distro is armbian
  ansible.builtin.stat:
    path: /etc/armbian-release
  register: openmediavault_armbian

- name: Armbian specific tuning
  ansible.builtin.include_tasks:
    file: armbian-specific.yml
  when: openmediavault_armbian.stat.isreg is defined and openmediavault_armbian.stat.isreg

- name: Radxa ROCK 5 ITX specific tuning
  ansible.builtin.include_tasks:
    file: rock-5-itx-specific.yml
  when: openmediavault_motherboard.stdout == '"Radxa ROCK 5 ITX"'

- name: Install Openmediavault
  ansible.builtin.include_tasks:
    file: install.yml
  when: openmediavault_keyring.stat.exists

- name: Configure Openmediavault
  ansible.builtin.include_tasks:
    file: configure.yml
