apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile-secrets
  namespace: seafile
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: seafile-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: MARIA_ROOT_PASSWORD
      remoteRef:
        key: app-seafile-secrets
        property: maria_root_password
    - secretKey: INIT_SEAFILE_ADMIN_PASSWORD
      remoteRef:
        key: app-seafile-secrets
        property: init_seafile_admin_password
    - secretKey: INIT_SEAFILE_ADMIN_EMAIL
      remoteRef:
        key: app-seafile-secrets
        property: init_seafile_admin_email
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: app-seafile-secrets
        property: jwt_private_key
    - secretKey: REDIS_PASS
      remoteRef:
        key: app-seafile-secrets
        property: redis_pass
    - secretKey: REDIS_CONF
      remoteRef:
        key: app-seafile-secrets
        property: redis_conf
    - secretKey: SEAFILE_MYSQL_DB_PASSWORD
      remoteRef:
        key: app-seafile-secrets
        property: seafile_mysql_db_password