- name: WAN servers
  hosts: wan-servers
  become: true
  gather_facts: false
  vars_files:
    - ./vault.yml
  vars:
    node_exporter_port: 9101
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - common
    - nginx
    - role: node-exporter
      tags: [observability]
    - role: wireguard
      tags: [vpn]
    - role: technitium
      tags: [dns]

- name: NAS servers
  hosts: nas-servers
  become: true
  gather_facts: false
  vars_files:
    - ./vault.yml
  vars:
    node_exporter_port: 9101
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - openmediavault
    - role: node-exporter
      tags: [observability]

- name: Lan servers
  hosts: lan-servers
  become: true
  gather_facts: false
  vars_files:
    - ./vault.yml
  vars:
    node_exporter_port: 9101
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - common
    - role: node-exporter
      tags: [observability]
    - role: technitium
      tags: [dns]
    - role: alloy
      tags: [observability]
    - role: prometheus
      tags: [observability]
    - gh-runner
    - role: wireguard
      tags: [vpn]
    - nginx

- name: Dev servers
  tags: dev
  hosts: dev-servers
  become: true
  roles:
    - k3s
