- name: Nym servers
  hosts: nym-servers
  become: true
  gather_facts: false
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - common
    - nym-node

- name: Prometheus servers
  hosts: prometheus-servers
  become: true
  gather_facts: false
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - common
    - prometheus

- name: Wireguard servers
  hosts: wireguard-servers
  become: true
  gather_facts: false
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - common
    - wireguard

- name: Technitium servers
  hosts: technitium-servers
  become: true
  gather_facts: false
  pre_tasks:
    - name: Import pre_tasks
      ansible.builtin.import_tasks: 'roles/common/knocking.yml'
  roles:
    - common
    - technitium