apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: radicale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#TODO: pass to storageClassName: saved-local-path when ready
