apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seafile
  namespace: seafile
spec:
  secretName: domain-tls # <===  Name of secret where the generated certificate will be stored.
  dnsNames:
    - <SEAFILE_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
