apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seafile
  namespace: seafile
spec:
  secretName: domain-tls
  commonName: <SEAFILE_DOMAIN>
  dnsNames:
    - <SEAFILE_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
