apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seafile-data
  namespace: seafile
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      middlewares:
        - name: stripprefix
          namespace: seafile
      match: <SEAFILE_DATA_MATCH> # WARN relies on prefix /seafhttp
      services:
        - name: seafile
          namespace: seafile
          port: 8082
