apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-seafile.yml
  - deploy-mariadb.yml
  - deploy-memcached.yml
  - deploy-seafile.yml
  - ingressroute-seafile-data.yml
  - ingressroute-seafile.yml
  - middleware-stripprefix.yml
  - ns-seafile.yml
  - pvc-mariadb-data.yml
  - pvc-seafile.yml
  - svc-mariadb.yml
  - svc-memcached.yml
  - svc-seafile.yml

secretGenerator:
  - name: seafile-secrets
    namespace: seafile
    envs:
      - .seafile.secret.env

configMapGenerator:
  - name: cluster-variables
    namespace: seafile
    envs:
      - .seafile.env

replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-variables
      namespace: seafile
      fieldPath: data.SEAFILE_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: seafile
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-variables
      namespace: seafile
      fieldPath: data.SEAFILE_DATA_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: seafile-data
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-variables
      namespace: seafile
      fieldPath: data.SEAFILE_DOMAIN
    targets:
      - select:
          kind: IngressRoute
          name: seafile
        fieldPaths:
          - spec.tls.domains.0.main
      - select:
          kind: IngressRoute
          name: seafile-data
        fieldPaths:
          - spec.tls.domains.0.main
      - select:
          kind: Certificate
          name: seafile
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
      - select:
          kind: Deployment
          name: seafile
        fieldPaths:
          - spec.template.spec.containers.[name=seafile].env.[name=SEAFILE_SERVER_HOSTNAME].value
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-variables
      namespace: seafile
      fieldPath: data.SEAFILE_STORAGE_SIZE
    targets:
      - select:
          kind: PersistentVolumeClaim
          name: seafile-data
        fieldPaths:
          - spec.resources.requests.storage
