# Pas pris en compte
apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data
  namespace: seafile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/seafile-data
