apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser
  namespace: media
spec:
  secretName: domain-tls
  commonName: browser.enki.sin
  dnsNames:
    - browser.enki.sin
    - browser.enki.sin:8443
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
