apiVersion: 1

datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: Loki
    # <string, required> Sets the data source type.
    type: loki
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    url: http://loki:80
    isDefault: false
    basicAuth: true
    basicAuthUser: loki 
    secureJsonData:
      basicAuthPassword: $__file{/var/run/secrets/loki_password}
