apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-secrets
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: loki-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: .HTACCESS
      remoteRef:
        key: app-loki-secrets
        property: .htaccess
    - secretKey: PASSWORD
      remoteRef:
        key: app-loki-secrets
        property: password