global:
  namespace: "openbao"
  tlsDisable: false
injector:
  gid: 61008
  uid: 61008
server:
  standalone:
    enabled: true
    config: |
      ui = true
      log_level = "info"

      initialize "identity" {
        request "add-superuser-policy" {
          operation = "update"
          path = "sys/policies/acl/superuser"
          data = {
            policy = "path \"*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"] }"
          }
        }

        request "enable-userpass" {
          operation = "update"
          path = "sys/auth/userpass"
          data = {
            type = "userpass"
            description = "Username/password authentication"
          }
        }

        request "userpass-add-admin" {
          operation = "update"
          path = "auth/userpass/users/admin"
          data = {
            "password" = {
               eval_type = "string"
               eval_source = "file"
               path = "/var/run/secrets/openbao/admin_password"
            }
            policies = ["superuser"]
          }
        }
      }

      initialize "cluster-access" {
        request "add-cluster_reader-policy" {
          operation = "update"
          path = "sys/policies/acl/cluster_reader"
          data = {
            policy = "path \"cluster/*\" { capabilities = [\"read\", \"list\"] }"
          }
        }

        request "enable-kubernetes-auth-method" {
          operation = "update"
          path = "sys/auth/kubernetes"
          data = {
            type = "kubernetes",
            description = "Login with a kube service account from a trusted cluster"
          }
        }

        request "configure-kube-auth" {
          operation = "update"
          path = "auth/kubernetes/config"
          data = {
            kubernetes_host = "https://kubernetes.default.svc.cluster.local"
          }
        }

        request "bind-cluster_reader-to_kube-auth" {
          operation = "update"
          path = "auth/kubernetes/role/cluster_reader"
          data = {
            bound_service_account_names = "external-secret-manager"
            bound_service_account_namespaces = "external-secrets"
            alias_name_source = "serviceaccount_name"
            token_policies = ["cluster_reader"]
          }
        }
      }

      initialize "secrets-collections" {
        request "create-cluster-secret-collection" {
          operation = "update"
          path = "sys/mounts/cluster"
          data = {
            type = "kv"
            options = {
              version = "2"
            }
          }
        }
      }


      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/var/run/secrets/openbao-tls/tls.crt"
        tls_key_file = "/var/run/secrets/openbao-tls/tls.key"
      }

      audit "file" "to-stdout" {
        description = "This audit device should never fail."
        options {
          file_path = "/dev/stdout"
          log_raw = "true"
        }
      }

      #storage "raft"
      storage "file" {
          path = "/data"
        }

      # openbao.org/docs/configuration/seal/
      seal "static" {
        current_key_id = "20260314-1"
        current_key = "file:///data/secrets/unseal-20260314-1.key"
      }
      #service_registration "kubernetes" {}
  ha:
    enabled: false
  dataStorage:
    # externaly handled
    enabled: false
  volumes:
    - name: openbao-data
      persistentVolumeClaim:
        claimName: openbao-data
    - name: openbao-secrets
      secret:
        secretName: openbao-secrets
    - name: openbao-internal-tls
      secret:
        secretName: openbao-internal-tls
  volumeMounts:
    - name: openbao-data
      mountPath: /data
    - name: openbao-secrets
      mountPath: /var/run/secrets/openbao
      readOnly: true
    - name: openbao-internal-tls
      mountPath: /var/run/secrets/openbao-tls
  extraInitContainers:
    - name: key-injector
      image: alpine
      command: [ash, -c]
      args:
        - mkdir -p /data/secrets && cat /var/run/key >
          /data/secrets/unseal-20260314-1.key
      volumeMounts:
        - name: openbao-data
          mountPath: /data
        - name: openbao-secrets
          mountPath: /var/run/key
          subPath: static_seal_key
          readOnly: true
