apiVersion: apps/v1
kind: Deployment
metadata:
  name: saved-path-provisioner
  namespace: custom-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saved-path-provisioner
  template:
    metadata:
      labels:
        app: saved-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
        - name: saved-path-provisioner
          image: rancher/local-path-provisioner:v0.0.31
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
