apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrolebinding-saved-path-provisioner.yml
  - cm-local-path-config.yml
  - deploy-saved-path-provisioner.yml
  - ns-custom-storage.yml
  - rolebinding-saved-path-provisioner.yml
  - role-saved-path-provisioner.yml
  - sa-local-path-provisioner.yml
  - storageclass-saved-local-path.yml
