apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: saved-local-path
provisioner: zar3bski.com/saved-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
