apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: saved-local-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
