apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: helloworld
  namespace: hello
spec:
  secretName: domain-tls # <===  Name of secret where the generated certificate will be stored.
  dnsNames:
    - <HELLO_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
