apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fail2ban-hello
  namespace: hello
spec:
  plugin:
    fail2ban:
      logLevel: DEBUG
      rules:
        urlregexps:
          - regexp: "/login"
            mode: filtered
        bantime: "5m"
        findtime: "5m"
        maxretry: 3
        enabled: true
        statuscode: "400,401,403-499"
