apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seafile
  namespace: seafile
spec:
  secretName: domain-tls
  commonName: file.enki.sin:8443
  dnsNames:
    - file.enki.sin:8443
    - file.enki.sin
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
