apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-seafile.yml
  - deploy-mariadb.yml
  - deploy-redis.yml
  - deploy-seafile.yml
  - ingressroute-seafile-data.yml
  - ingressroute-seafile.yml
  - middleware-stripprefix.yml
  - ns-seafile.yml
  - pvc-mariadb-data.yml
  - pvc-seafile.yml
  - svc-mariadb.yml
  - svc-redis.yml
  - svc-seafile.yml
