apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-variables
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: cluster-variables
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: TZ
      remoteRef:
        key: cluster-common
        property: timezone