apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-middleware-oidc
  namespace: transmission
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: traefik-middleware-oidc
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: app-transmission-oidc
        property: client_id
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: app-transmission-oidc
        property: client_secret
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: app-transmission-oidc
        property: encryption_key
    - secretKey: ISSUER
      remoteRef:
        key: cluster-oidc
        property: issuer