apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-vault
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://openbao.openbao.svc.cluster.local:8200"
      path: "cluster/"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "cluster_reader"
          serviceAccountRef:
            name: "external-secret-manager"
            namespace: "external-secrets"
      caProvider:
        type: ConfigMap
        namespace: external-secrets
        name: kube-root-ca.crt
        key: ca.crt
