{
 "title": "Wireguard by Instance",
 "description": "Metrics for Wireguard VPN",
 "tags": [
  "wireguard",
  "VPN",
  "network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(wireguard_latest_handshake_delay_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connected Clients (SI)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(public_key, friendly_name) (rate(wireguard_received_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(public_key, friendly_name) (rate(wireguard_received_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(public_key, friendly_name) (rate(wireguard_sent_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{allowed_ips}}"
    }
   ]
  },
  {
   "title": "Latest Handshakes (Seconds)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(public_key, friendly_name, allowed_ip_0) (rate(wireguard_latest_handshake_seconds{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{allowed_ip_0}}:{{friendly_name}}"
    }
   ]
  }
 ]
}