- name: Create a alertmanager user
  ansible.builtin.user:
    name: alertmanager
    create_home: true
    shell: /bin/rbash # Restricted shell
    uid: 1006
    groups:
      - docker

- name: Create a data folder
  ansible.builtin.file:
    path: /home/alertmanager/conf
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: "0750"

- name: Configuration templating
  ansible.builtin.template:
    src: templates/alertmanager.yml.j2
    dest: /home/alertmanager/conf/config.yml
    mode: "0750"
    owner: alertmanager
    group: alertmanager

- name: Create Alermanager service
  block:
    - name: Create systemd conf file
      ansible.builtin.template:
        src: templates/alertmanager.service.j2
        dest: /etc/systemd/system/alertmanager.service
        mode: "0750"
    - name: Enable and start service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        enabled: true
        name: alertmanager
