- name: Gathering facts
  ansible.builtin.setup:

- name: Install docker
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - ca-certificates

    - name: Identify distro # noqa: no-changed-when
      ansible.builtin.shell: ". /etc/os-release && echo $VERSION_CODENAME"
      register: version

    - name: Identify arch # noqa: no-changed-when
      ansible.builtin.command: "dpkg --print-architecture"
      register: arch

    - name: Identify distro # noqa: no-changed-when
      ansible.builtin.shell: ". /etc/os-release && echo $ID"
      register: distro

    - name: Copy keyring
      ansible.builtin.get_url:
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add docker repository # noqa: yaml[line-length]
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ distro.stdout }} {{ version.stdout }} stable"
        state: present
        filename: docker

    - name: Install docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

- name: Create a prometheus user
  ansible.builtin.user:
    name: prometheus
    create_home: true
    shell: /bin/rbash  # Restricted shell
    uid: 1001
    groups:
      - docker

- name: Create a prometheus data folder
  ansible.builtin.file:
    path: /home/prometheus/data
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Create prometheus service
  block:
    - name: Create systemd conf file
      ansible.builtin.template:
        src: templates/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: '0755'
    - name: Enable and start service
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: true
        name: prometheus
