- name: Create a prometheus user
  ansible.builtin.user:
    name: prometheus
    create_home: true
    shell: /bin/rbash # Restricted shell
    uid: 1003
    groups:
      - docker

- name: Create a prometheus data folder
  ansible.builtin.file:
    path: /home/prometheus/data
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0750"

- name: Create a prometheus conf folder
  ansible.builtin.file:
    path: /home/prometheus/conf
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0750"

- name: Main conf templating
  ansible.builtin.template:
    src: templates/prometheus.yml.j2
    dest: /home/prometheus/conf/prometheus.yml
    mode: "0750"
    owner: prometheus
    group: prometheus

- name: Create prometheus service
  block:
    - name: Create systemd conf file
      ansible.builtin.template:
        src: templates/prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: "0750"
    - name: Enable and start service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        enabled: true
        name: prometheus
