{
 "title": "Logs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "label": "Node name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global journald",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"loki.source.journal.journalctl\", node_name=\"$node_name\"} |= ``"
    }
   ]
  },
  {
   "title": "Cron",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=\"cron.service\", node_name=\"$node_name\"}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Traefik",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"kube-system/traefik\"}"
    }
   ]
  }
 ]
}