apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: saved-path-provisioner-role
  namespace: custom-storage
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
