apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cluster-variables
    envs: [./.env]
    behavior: create
    namespace: kube-system

resources:
  - helmchartconfig-traefik.yml
