apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-wildcard-domain-tls.yml
  - helmchartconfig-traefik.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cluster-variables
    envs: [./.network.env]
    behavior: create
    namespace: kube-system

replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-variables
      namespace: kube-system
      fieldPath: data.WILDCARD_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: wildcard-domain-tls
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
