apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: filebrowser
    newName: gtstef/filebrowser
    newTag: 0.7.11-beta-slim

resources:
  - certificate-filebrowser.yml
  - cm-filebrowser-config-tpl.yml
  - deploy-filebrowser.yml
  - es-filebrowser-config.yml
  - ingressroute-filebrowser.yml
  - svc-filebrowser.yml



