apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
spec:
  selector:
    matchLabels:
      app: seafile
  template:
    spec:
      containers:
        - name: seafile
          env:             
            - name: SEAFILE_SERVER_HOSTNAME
              value: file.alpine.dev.local
