apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: hello
    newName: nginx
    newTag: 1.28.0-alpine3.21

generatorOptions:
  disableNameSuffixHash: true

resources:
  - es-hello-oidc.yml
  - ns-hello.yml
  - middleware-fail2ban-hello.yml
  - middleware-oidc-hello.yml
  - deploy-helloworld.yml
  - svc-helloworld.yml
  - certificate-helloworld.yml
  - ingressroute-helloworld.yml

configMapGenerator:
  - name: hello-variables
    envs: [./.hello.env]
    behavior: create
    namespace: hello


replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: hello-variables
      namespace: hello
      fieldPath: data.HELLO_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: helloworld
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: ConfigMap
      version: v1
      name: hello-variables
      namespace: hello
      fieldPath: data.HELLO_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: helloworld
        fieldPaths:
          - spec.routes.0.match
