apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  - certificate-observability.yml
  - cm-grafana.yml
  - deploy-grafana.yml
  - ingressroute-observability.yml
  - ns-observability.yml
  - pvc-grafana.yml
  - svc-grafana.yml

secretGenerator:
  - name: grafana-secrets
    namespace: observability
    envs:
      - .grafana-secrets.env

configMapGenerator:
  - name: observability-variables
    namespace: observability
    envs:
      - .observability.env

replacements:
  - source:
      kind: ConfigMap
      name: observability-variables
      namespace: observability
      fieldPath: data.GRAFANA_ROOT_URL
    targets:
      - select:
          kind: Deployment
          name: grafana
        fieldPaths:
          - spec.template.spec.containers.[name=grafana].env.[name=GF_SERVER_ROOT_URL].value
  - source:
      kind: ConfigMap
      name: observability-variables
      namespace: observability
      fieldPath: data.GRAFANA_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: observability
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: ConfigMap
      name: observability-variables
      namespace: observability
      fieldPath: data.GRAFANA_DOMAIN
    targets:
      - select:
          kind: IngressRoute
          name: observability
        fieldPaths:
          - spec.tls.domains.0.main
      - select:
          kind: Certificate
          name: observability
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
