apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: media
spec:
  selector:
    matchLabels:
      app: transmission
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 33333
      initContainers:
        - name: volume-rights-setter
          image: busybox:1.37.0-glibc
          command:
            - /bin/sh
          args:
            - -c
            - chown -R 65534:33333 /downloads
            - chmod 775 /downloads
          volumeMounts:
            - name: transmission-downloads
              mountPath: /downloads
          securityContext:
            runAsUser: 0
            runAsGroup: 0

      containers:
        - name: transmission
          image: transmission
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: cluster-variables
                  key: TZ
          volumeMounts:
            - name: transmission-downloads
              mountPath: /downloads
            - name: transmission-config
              mountPath: /config
          ports:
            - containerPort: 9091
            - containerPort: 51413
              protocol: TCP
            - containerPort: 51413
              protocol: UDP
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 600Mi
      volumes:
        - name: transmission-downloads
          persistentVolumeClaim:
            claimName: transmission-downloads
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config
