# Source: reflector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reflector
  namespace: kube-system
  labels:
    helm.sh/chart: reflector-9.1.7
    app.kubernetes.io/name: reflector
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/version: "9.1.7"
    app.kubernetes.io/managed-by: Helm
