apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  secretName: domain-tls
  dnsNames:
    - <VAULT_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
