apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`vault.enki.sin`) && PathPrefix(`/`)
      observability:
        accessLogs: true
        metrics: true
      services:
        - name: vaultwarden
          namespace: vaultwarden
          port: 80
  tls:
    secretName: domain-tls
    domains:
      - main: vault.enki.sin
