apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: vaultwarden
    newName: vaultwarden/server
    newTag: 1.33.2-alpine
  - name: bitwarden-cli
    newName: zar3bski/bitwarden-cli
    newTag: "2025.5.0"

resources:
  - certificate-vaultwarden.yml
  - deploy-vaultwarden.yml
  - ingressroute-vaultwarden.yml
  - ns-vaultwarden.yml
  - pvc-vaultwarden.yml
  - svc-vaultwarden.yml

configMapGenerator:
  - name: vaultwarden-config
    namespace: vaultwarden
    envs:
      - .vaultwarden.env

replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: vaultwarden-config
      namespace: vaultwarden
      fieldPath: data.VAULT_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: vaultwarden
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: vaultwarden
        fieldPaths:
          - spec.tls.domains.0.main
  - source:
      kind: ConfigMap
      version: v1
      name: vaultwarden-config
      namespace: vaultwarden
      fieldPath: data.VAULTWARDEN_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: vaultwarden
        fieldPaths:
          - spec.routes.0.match
